function A0 = genA_1_by_MPC_bool(X,x_dot,Y,y_dot,phi,phi_dot,Ccf,Ccr,I,lf,lr,delta_f,m)
%genA_1_by_MPC_bool
%    A0 = genA_1_by_MPC_bool(X,X_DOT,Y,Y_DOT,PHI,PHI_DOT,Ccf,Ccr,I,LF,LR,DELTA_F,M)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Dec-2023 23:56:57

t2 = cos(phi);
t3 = sin(phi);
t4 = lf.*phi_dot;
t5 = lr.*phi_dot;
t6 = m.*phi_dot;
t7 = 1.0./I;
t8 = 1.0./m;
t9 = 1.0./x_dot;
t10 = t9.^2;
t11 = t4+y_dot;
t12 = -t5;
t14 = Ccf.*lf.*t9.*2.0;
t15 = Ccr.*lr.*t9.*2.0;
t13 = t12+y_dot;
t16 = -t15;
A0 = reshape([-t8.*(Ccf.*t9.*2.0+Ccr.*t9.*2.0),t8.*(t6-Ccf.*delta_f.*t9.*2.0),0.0,-t7.*(t14+t16),t2,-t3,-t8.*(t6-Ccf.*t10.*t11.*2.0+Ccr.*t10.*(t5-y_dot).*2.0),Ccf.*delta_f.*t8.*t10.*t11.*2.0,0.0,t7.*(Ccr.*lr.*t10.*(t5-y_dot).*2.0+Ccf.*lf.*t10.*t11.*2.0),t3,t2,0.0,0.0,0.0,0.0,t2.*x_dot-t3.*y_dot,-t3.*x_dot-t2.*y_dot,-t8.*(t14+t16+m.*x_dot),t8.*(m.*y_dot-Ccf.*delta_f.*lf.*t9.*2.0),1.0,-t7.*(lf.*t14+lr.*t15),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
