function B0 = genB_1_by_MPC_bool(X,x_dot,Y,y_dot,phi,phi_dot,Ccf,Ccr,I,lf,lr,delta_f,m,Clf,Clr,Sf,Sr)
%genB_1_by_MPC_bool
%    B0 = genB_1_by_MPC_bool(X,X_DOT,Y,Y_DOT,PHI,PHI_DOT,Ccf,Ccr,I,LF,LR,DELTA_F,M,Clf,Clr,Sf,Sr)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    19-Dec-2023 00:14:57

t2 = 1.0./m;
B0 = [Ccf.*t2.*2.0;t2.*(Ccf.*delta_f.*2.0+Ccf.*(delta_f-(y_dot+lf.*phi_dot)./x_dot).*2.0);0.0;(Ccf.*lf.*2.0)./I;0.0;0.0];
