function A0 = genA_1_by_MPC_threedof_forge0311(X,x_dot,Y,y_dot,phi,phi_dot,Ccf,Ccr,I,lf,lr,delta_f,m,Clf,Clr,Sf,Sr,Fx)
%genA_1_by_MPC_threedof_forge0311
%    A0 = genA_1_by_MPC_threedof_forge0311(X,X_DOT,Y,Y_DOT,PHI,PHI_DOT,Ccf,Ccr,I,LF,LR,DELTA_F,M,Clf,Clr,Sf,Sr,Fx)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Mar-2024 19:15:18

t2 = cos(delta_f);
t3 = cos(phi);
t4 = sin(delta_f);
t5 = sin(phi);
t6 = Ccr.*lr;
t7 = lf.^2;
t8 = lr.^2;
t10 = 1.0./I;
t11 = 1.0./m;
t12 = 1.0./x_dot;
t9 = Ccf.*t2;
t13 = t12.^2;
t14 = lr.*t6;
t15 = lf.*t9;
t16 = Ccr+t9;
t17 = t7.*t9;
t18 = -t15;
t20 = t14+t17;
t19 = t6+t18;
A0 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t3,Ccf.*t4.*t11.*t13.*y_dot+Ccf.*lf.*phi_dot.*t4.*t11.*t13,t5,-phi_dot+phi_dot.*t11.*t13.*t19-t11.*t13.*t16.*y_dot,0.0,-phi_dot.*t10.*t13.*t20+t10.*t13.*t19.*y_dot,0.0,0.0,0.0,0.0,0.0,0.0,-t5,phi_dot-Ccf.*t4.*t11.*t12,t3,t11.*t12.*t16,0.0,-t10.*t12.*t19,-t5.*x_dot-t3.*y_dot,0.0,t3.*x_dot-t5.*y_dot,0.0,0.0,0.0,0.0,y_dot-Ccf.*lf.*t4.*t11.*t12,0.0,-x_dot-t11.*t12.*t19,1.0,t10.*t12.*t20],[6,6]);
