function B0 = genB_1_by_MPC_threedof_forge0311(X,x_dot,Y,y_dot,phi,phi_dot,Ccf,Ccr,I,lf,lr,delta_f,m,Clf,Clr,Sf,Sr,Fx)
%genB_1_by_MPC_threedof_forge0311
%    B0 = genB_1_by_MPC_threedof_forge0311(X,X_DOT,Y,Y_DOT,PHI,PHI_DOT,Ccf,Ccr,I,LF,LR,DELTA_F,M,Clf,Clr,Sf,Sr,Fx)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Mar-2024 19:15:23

t2 = cos(delta_f);
t3 = sin(delta_f);
t4 = 1.0./I;
t5 = 1.0./m;
t6 = 1.0./x_dot;
B0 = reshape([0.0,t2.*t5,0.0,t3.*t5,0.0,lf.*t3.*t4,0.0,Ccf.*t3.*t5-Fx.*t3.*t5+Ccf.*delta_f.*t2.*t5-Ccf.*t2.*t5.*t6.*y_dot-Ccf.*lf.*phi_dot.*t2.*t5.*t6,0.0,-Ccf.*t2.*t5+Fx.*t2.*t5+Ccf.*delta_f.*t3.*t5-Ccf.*t3.*t5.*t6.*y_dot-Ccf.*lf.*phi_dot.*t3.*t5.*t6,0.0,-Ccf.*lf.*t2.*t4+Fx.*lf.*t2.*t4+Ccf.*delta_f.*lf.*t3.*t4-Ccf.*lf.^2.*phi_dot.*t3.*t4.*t6-Ccf.*lf.*t3.*t4.*t6.*y_dot],[6,2]);
