function B0 = genB_7dof_0316(X,x_dot,Y,y_dot,phi1,phi2,Ccf,Ccr,I,lf,lr,delta_f,m,Clf,Clr,Sf,Sr,Fx)
%genB_7dof_0316
%    B0 = genB_7dof_0316(X,X_DOT,Y,Y_DOT,PHI1,PHI2,Ccf,Ccr,I,LF,LR,DELTA_F,M,Clf,Clr,Sf,Sr,Fx)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Mar-2024 12:01:28

t2 = cos(delta_f);
t3 = cos(phi1);
t4 = sin(delta_f);
t5 = sin(phi1);
t6 = lf.^2;
t7 = 1.0./I;
t8 = 1.0./m;
t9 = 1.0./x_dot;
B0 = reshape([0.0,0.0,0.0,0.0,t4.*t8,0.0,lf.*t4.*t7,0.0,0.0,0.0,0.0,-Ccf.*t2.*t8+Fx.*t2.*t8+Ccf.*delta_f.*t4.*t8-Ccf.*t4.*t8.*t9.*y_dot-Ccf.*lf.*phi2.*t4.*t8.*t9,0.0,-Ccf.*lf.*t2.*t7+Fx.*lf.*t2.*t7+Ccf.*delta_f.*lf.*t4.*t7-Ccf.*phi2.*t4.*t6.*t7.*t9-Ccf.*lf.*t4.*t7.*t9.*y_dot,-t5.*x_dot-t3.*y_dot,1.0,0.0,t3.*x_dot-t5.*y_dot,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-x_dot-t8.*t9.*(Ccr.*lr-Ccf.*lf.*t2),1.0,t7.*t9.*(Ccr.*lr.^2+Ccf.*t2.*t6)],[7,4]);
